name: phounsouk
favicon: null
layout_spectrum: 0.37163
typography_spectrum: 0.94654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07222d'
    - '#00040a'
    - '#0f435b'
    - '#15678d'
    - '#277aa1'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
